# Generated by Django 4.1.6 on 2023-03-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['id'], 'verbose_name': 'menu', 'verbose_name_plural': 'menus'},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='is_root',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='leaves',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='url',
        ),
        migrations.AddField(
            model_name='menu',
            name='json',
            field=models.TextField(default={'name': 'Test', 'sub_menus': [{'name': 'sub_test', 'sub_menus': [{'name': 'sub_sub_test', 'url': '#'}]}, {'name': 'sub_test', 'sub_menus': [{'name': 'sub_sub_test', 'url': '#'}]}]}),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(default='test', max_length=50),
        ),
    ]
