# Generated by Django 4.1.6 on 2023-03-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_alter_menu_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='json',
            field=models.TextField(default=''),
        ),
    ]
