# Generated by Django 4.1.6 on 2023-03-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_alter_menu_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(default='test', max_length=50, unique=True),
        ),
    ]
