# Generated by Django 4.1.6 on 2023-03-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_alter_menu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='json',
            field=models.TextField(default="{'name': 'Test', 'sub_menus': [{'name': 'sub_test', 'sub_menus': [{'name': 'sub_sub_test', 'url': '#'}]}, {'name': 'sub_test', 'sub_menus': [{'name': 'sub_sub_test', 'url': '#'}]}]}"),
        ),
    ]
