# Generated by Django 4.1.6 on 2023-03-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0008_alter_menu_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='json',
            field=models.TextField(default={'name': 'Test', 'sub_menus': [{'name': 'sub_test', 'sub_menus': [{'name': 'sub_sub_test', 'title': 'Уровень 1.1.1', 'url': '#'}], 'title': 'Уровень 1.1'}, {'name': 'sub_test', 'sub_menus': [{'name': 'sub_sub_test', 'title': 'Уровень 2.1', 'url': '#'}], 'title': 'Уровень 2'}], 'title': 'Уровень 1.0'}),
        ),
    ]
